core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("pages.urls")),
    path('admin/', admin.site.urls),
    path('quiz/', include('quiz.urls', namespace='quiz')),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("articles/", include("articles.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/urls.py
from . import views
from django.urls import path
from .views import Quiz, RandomQuestion, QuizQuestion, get_question_with_answers, question_page, result_view
from django.conf import settings
from django.conf.urls.static import static


app_name='quiz'

urlpatterns = [
    path('', views.Quiz.as_view(), name='home'),
    path('question/<int:question_id>/', views.get_question_with_answers, name='question_with_answers'),
    path('quiz/<int:quiz_id>/', views.question_page, name='question_page'),
    path('quiz/result<int:quiz_id>/', views.result_view, name='quiz_result'),
    path('quiz/submit-answer/<int:quiz_id>/', views.submit_answer, name='submit-answer'),
    path('submit-answer/<int:quiz_id>/', views.submit_answer, name='submit_answer'),
    path('quizzes/', views.quiz_list, name='quiz_list'),
    path('quizzes/create/', views.create_quiz, name='create_quiz'),
    path('quizzes/category/', views.create_category, name='create_category'),
    path('quizzes/category/list/', views.category_list, name='category_list'),
    path('quizzes/question/create', views.create_question, name='create_question'),
    path('quizzes/question/list', views.question_list, name='question_list'),
    path('r/<str:topic>', views.RandomQuestion.as_view(), name='random'),
    path('q/<str:topic>', views.QuizQuestion.as_view(), name='questions'),
    path('scores/', views.user_scores, name='scores')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    

class Quizzes(models.Model):

    class Meta:
        verbose_name = _("Quiz")
        verbose_name_plural = _("Quizzes")
        ordering = ['id']

    title = models.CharField(max_length=255, default=_("New Quiz"), verbose_name=_("Quiz Title"))

    category = models.ForeignKey(Category, default=1, on_delete=models.DO_NOTHING)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Updated(models.Model):

    date_updated = models.DateTimeField(verbose_name=_("Last Updated"), auto_now=True)

    class Meta:
        abstract = True

class Question(Updated):

    class Meta:
        verbose_name = _("Question")
        verbose_name_plural = _("Questions")
        ordering = ['id']

    SCALE = (
        (0, _('Fundamental')),
        (1, _('Beginner')),
        (2, _('Intermediate')),
        (3, _('Advanced')),
        (4, _('Expert'))
    )

    TYPE = (
        (0, _('Multiple Choice')),
    )

    quiz = models.ForeignKey(Quizzes, related_name='question', on_delete=models.DO_NOTHING)
    technique = models.IntegerField(choices=TYPE, default=0, verbose_name=_("Type of Question"))
    title = models.CharField(max_length=255, verbose_name=_("Title"))
    difficulty = models.IntegerField(choices=SCALE, default=0, verbose_name=_("Difficulty"))
    data_created = models.DateTimeField(auto_now_add=True, verbose_name=_("Data Created"))
    is_active = models.BooleanField(default=False, verbose_name=_("Active Status"))

    def __str__(self):
        return self.title

class Answer(Updated):

    class Meta:
        verbose_name = _("Answer")
        verbose_name_plural = _("Answers")
        ordering = ['id']

    question = models.ForeignKey(Question, related_name='answer', on_delete=models.DO_NOTHING)
    answer_text = models.CharField(max_length=255, verbose_name=_("Answer Text"))
    is_right = models.BooleanField(default=False)

    def __str__(self):
        return self.answer_text

class QuizAttempt(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quizzes, on_delete=models.CASCADE)
    score = models.IntegerField()

    def __str__(self):
        return f"{self.user.username} - {self.quiz.title} - Score: {self.score}"
    
class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)


    def __str__(self):
        return self.user.username

quiz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework.response import Response
from .models import Quizzes, Question, Category, Answer, QuizAttempt
from .serializers import QuizSerializer, QuestionSerializer, RandomQuestionSerializer
from rest_framework.views import APIView
from .forms import CategoryForm, CreateQuizForm, QuestionForm, AnswerForm, CreateQuestionForm, AnswerFormSet
from django.forms import formset_factory
from django.contrib.auth.decorators import login_required
from .models import UserProfile
from django.contrib.auth.models import User
from accounts.models import CustomUser
from django.db.models import Sum


class Quiz(APIView):

    def get(self, request, format=None):
        quizzes = Quizzes.objects.all()
        serializer = QuizSerializer(quizzes, many=True)
        return Response(serializer.data)

class RandomQuestion(APIView):

    def get(self, request, topic, format=None):
        question = Question.objects.filter(quiz__title=topic).order_by('?')[:1]
        serializer = RandomQuestionSerializer(question, many=True)
        return Response(serializer.data)

class QuizQuestion(APIView):

    def get(self, request, topic, format=None):
        question = Question.objects.filter(quiz__title=topic)
        serializer = QuestionSerializer(question, many=True)
        return Response(serializer.data)

def get_question_with_answers(request, question_id):
    question = Question.objects.get(id=question_id)
    answers = question.answer.all()

    context = {
        'question': question,
        'answers': answers
    }
    return render(request, 'question_with_answers.html', context)

def question_page(request, quiz_id):
    quiz = Quizzes.objects.get(id=quiz_id)
    questions = Question.objects.filter(quiz__id=quiz_id)

    
    context = {
        'quiz': quiz,
        'questions': questions,
    }
    return render(request, 'quiz/question_page.html', context)


def submit_answer(request, quiz_id):
    quiz = get_object_or_404(Quizzes, id=quiz_id)
    
    if request.method == 'POST':
        score = calculate_score(request, quiz_id)
        user_score = request.session.get('score', 0) 

        if score > user_score:
            user_score = score

        request.session['score'] = user_score 
        context = {
            'quiz_id': quiz_id,
            'score': user_score,
        }

        return render(request, 'quiz/quiz_result.html', context)
    else:
        context = {
            'quiz_id': quiz_id,
        }
        return render(request, 'quiz/answer_form.html', context)

def calculate_score(request, quiz_id):
    score = 0
    for question in request.POST:
        if question.startswith('question_'):
            selected_answer_id = request.POST[question]
            answer = Answer.objects.get(id=selected_answer_id)
            if answer.is_right:
                score += 1

    user = request.user

    user_profile, created = UserProfile.objects.get_or_create(user=user)
    user_profile.score += score
    user_profile.save()

    quiz = get_object_or_404(Quizzes, id=quiz_id)

    attempt = QuizAttempt.objects.create(user=user, quiz=quiz, score=score)

    return score

def result_view(request, quiz_id):
    score = calculate_score(request, quiz_id)  

    context = {
        'score': score,
    }

    return render(request, 'quiz/result.html', context)

def quiz_list(request):
    quizzes = Quizzes.objects.all()
    return render(request, 'quiz/quiz_list.html', {'quizzes': quizzes})

from django.shortcuts import redirect

def create_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quiz:create_quiz')
    else:
        form = CategoryForm()
    
    return render(request, 'quiz/create_category.html', {'form': form})


def category_list(request):
    categories = Category.objects.all()
    return render(request, 'quiz/category_list.html', {'categories': categories})

def create_quiz(request):
    if request.method == 'POST':
        form = CreateQuizForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.author = request.user
            quiz.save()
            return redirect('quiz:create_question')
    else:
        form = CreateQuizForm()

    return render(request, 'quiz/create_quiz.html', {'form': form})

def create_question(request):
    if request.method == 'POST':
        form = CreateQuestionForm(request.POST)
        formset = AnswerFormSet(request.POST)

        if form.is_valid() and formset.is_valid():
            question = form.save()  

            answers = formset.save(commit=False)  
            for answer in answers:
                answer.question = question
                answer.save()  

            return redirect('quiz:question_list') 
    else:
        form = CreateQuestionForm()
        formset = AnswerFormSet()

    return render(request, 'quiz/create_question.html', {'form': form, 'formset': formset})


def question_list(request):
    questions = Question.objects.all()
    return render(request, 'quiz/question_list.html', {'questions': questions})

def save_score(request, score):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)
    user_profile.score = score
    user_profile.save()

def quiz_results(request):
    user = request.user
    quiz_attempts = QuizAttempt.objects.filter(user=user)
    
    context = {
        'quiz_attempts': quiz_attempts
    }
    
    return render(request, 'quiz_results.html', context)


from django.db.models import Sum

def user_scores(request):
    user_profiles = CustomUser.objects.all()

    for user_profile in user_profiles:
        quiz_attempts = QuizAttempt.objects.filter(user=user_profile)
        scores_by_category = quiz_attempts.values('quiz__category').annotate(total_score=Sum('score'))

        total_score = 0
        for score in scores_by_category:
            total_score += score['total_score']

        if total_score is not None:
            user_profile.score = total_score
        else:
            user_profile.score = 0
        user_profile.scores_by_category = scores_by_category

        user_profile.save()

    context = {
        'user_profiles': user_profiles,
    }
    return render(request, 'quiz/scores.html', context)

def save_quiz_attempt(request, quiz_id, score):
    user = request.user

    quiz = Quizzes.objects.get(id=quiz_id)

    quiz_attempt, created = QuizAttempt.objects.get_or_create(user=user, quiz=quiz)

    if not created:
        quiz_attempt.score += score
        quiz_attempt.save()

    return score

def calculate_total_score(user_profile):
    total_score = user_profile.score
    user_profile.total_score = total_score
    user_profile.save()

templates/quiz/answer_form.html
<form action="{% url 'quiz:submit_answer' quiz_id=quiz.id %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="quiz_id" value="{{ quiz.id }}">
  <!-- Остальные поля формы -->
  <button type="submit">Submit</button>
</form>

templates/quiz/category_list.html
{% extends "base.html" %}

{% block title %}
    Category List
{% endblock title %}

{% block content %}
    <h1>Category List</h1>
    <ul>
        {% for category in categories %}
            <li>{{ category.name }}</li>
        {% empty %}
            <li>No categories found.</li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/quiz/create_category.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Category{% endblock title %}

{% block content %}
    <h1>Create Category</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Create</button>
    </form>
{% endblock content %}

templates/quiz/create_question.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h1 style="font-size: 24px; margin-bottom: 20px;">Create Question</h1>
  <form method="post" style="margin-bottom: 20px;">
    {% csrf_token %}
    {{ form|crispy }}

    {{ formset.management_form }}

    <fieldset style="border: none; margin: 0; padding: 0;">
      <legend style="font-weight: bold; margin-bottom: 10px;">Answer Options</legend>
      {% for form in formset %}
        <div class="form-field">
          {{ form.answer_text|as_crispy_field }}
          {{ form.is_right|as_crispy_field }}
          
        </div>
      {% endfor %}
    </fieldset>

    <button class="btn btn-success" type="submit" style="background-color: #4CAF50; color: white; border: none; padding: 10px 20px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; cursor: pointer;">
      Create
    </button>
  </form>
{% endblock %}

templates/quiz/create_quiz.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Quiz{% endblock title %}

{% block content %}
    <h1>Create Quiz</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Create</button>
    </form>
{% endblock content %}

templates/quiz/question_list.html
{% extends "base.html" %}

{% block title %}Question List{% endblock title %}

{% block content %}
  <h1>Question List</h1>
  <ul>
    {% for question in questions %}
      <li>{{ question.title }}</li>
    {% empty %}
      <li>No questions available.</li>
    {% endfor %}
  </ul>
{% endblock content %}

templates/quiz/question_page.html
{% extends "base.html" %}

{% load static %}

{% block title %}Answer Form{% endblock title %}

{% block content %}

    <body>
        <h1 class="quiz-title">{{ quiz.title|upper }}</h1>

        <form method="POST" action="{% url 'quiz:submit-answer' quiz.id %}">
            {% csrf_token %}

            {% for question in questions %}
                <h3>{{ question.title }}</h3>
                <ul>
                    {% for answer in question.answer.all %}
                        <li>
                            <label>
                                <input type="radio" name="question_{{ question.id }}" value="{{ answer.id }}">
                                {{ answer.answer_text }}
                            </label>
                        </li>
                    {% endfor %}
                </ul>
            {% endfor %}

            <input type="submit" value="Submit">
        </form>
    </body>
{% endblock content %}

templates/quiz/quiz_list.html
{% extends "base.html" %}

{% block title %}Quiz List{% endblock title %}

{% block content %}
    <h1>Quiz List</h1>
    <ul>
        {% for quiz in quizzes %}
        <li><a href="{% url 'quiz:question_page' quiz_id=quiz.id %}">{{ quiz.title }} - {{ quiz.description }}</a></li>
        {% empty %}
            <li>No quizzes available.</li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/quiz/quiz_result.html
{% extends "base.html" %}

{% block title %}Quiz Result{% endblock %}

{% block content %}
  <div class="container">
    <h1>Quiz Result</h1>

    <div class="score">
      Score: <strong>{{ score }}</strong>
    </div>

  </div>
{% endblock %}

templates/quiz/scores.html
{% extends "base.html" %}

{% block title %}User Scores{% endblock %}

{% block content %}
  <div class="container">
    <h1>User Scores</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Username</th>
          <th>Total Score</th>
        </tr>
      </thead>
      <tbody>
        {% for user_profile in user_profiles|dictsortreversed:"score" %}
          <tr>
            <td>{{ user_profile.username }}</td>
            <td>{{ user_profile.score }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}