core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("pages.urls")),
    path('admin/', admin.site.urls),
    path('quiz/', include('quiz.urls', namespace='quiz')),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("articles/", include("articles.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/urls.py
from . import views
from django.urls import path
from .views import Quiz, RandomQuestion, QuizQuestion, get_question_with_answers, question_page, result_view
from django.conf import settings
from django.conf.urls.static import static


app_name='quiz'

urlpatterns = [
    path('', views.Quiz.as_view(), name='home'),
    path('question/<int:question_id>/', views.get_question_with_answers, name='question_with_answers'),
    path('quiz/<int:quiz_id>/', views.question_page, name='question_page'),
    path('quiz/result<int:quiz_id>/', views.result_view, name='quiz_result'),
    path('quiz/submit-answer/<int:quiz_id>/', views.submit_answer, name='submit-answer'),
    path('submit-answer/<int:quiz_id>/', views.submit_answer, name='submit_answer'),
    path('quizzes/', views.quiz_list, name='quiz_list'),
    path('quizzes/create/', views.create_quiz, name='create_quiz'),
    path('quizzes/category/', views.create_category, name='create_category'),
    path('quizzes/category/list/', views.category_list, name='category_list'),
    path('quizzes/question/create', views.create_question, name='create_question'),
    path('quizzes/question/list', views.question_list, name='question_list'),
    path('r/<str:topic>', views.RandomQuestion.as_view(), name='random'),
    path('q/<str:topic>', views.QuizQuestion.as_view(), name='questions'),
    path('scores/', views.user_scores, name='scores')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/article_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
<p>Are you sure you want to delete "{{ article.title }}"?</p>
<button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

templates/article_detail.html
{% extends "base.html" %}
{% block content %}
<div class="article-entry">
<h2>{{ object.title }}</h2>
<p>by {{ object.author }} | {{ object.date }}</p>
<p>{{ object.body }}</p>
</div>
<p><a href="{% url 'article_edit' article.pk %}">Edit</a> |
<a href="{% url 'article_delete' article.pk %}">Delete</a></p>
<p>Back to <a href="{% url 'article_list' %}">All Posts</a>.</p>
{% endblock content %}

templates/article_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Edit</h1>
<form action="" method="post">{% csrf_token %}
{{ form|crispy }}
<button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}

templates/article_list.html
{% extends "base.html" %}
{% block title %}Articles{% endblock title %}
{% block content %}
  {% for article in article_list %}
    <div class="card">
      <div class="card-header">
        <span class="font-weight-bold">{{ article.title }}</span> &middot;
        <span class="text-muted">by {{ article.author }} | {{ article.date }}</span>
      </div>
      <div class="card-body">
        {{ article.body }}
      </div>
      {% if user.is_authenticated and user == article.author %}
        <div class="card-footer text-center text-muted">
          <a href="{% url 'article_edit' article.pk %}">Edit</a> |
          <a href="{% url 'article_delete' article.pk %}">Delete</a>
        </div>
      {% endif %}
    </div>
    <br />
  {% endfor %}

  <a href="{% url 'article_new' %}" class="btn btn-primary">New Post</a>
{% endblock content %}

templates/article_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1>New article</h1>
<form action="" method="post">{% csrf_token %}
{{ form|crispy }}
<button class="btn btn-success ml-2" type="submit">Save</button>
</form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}Quiz{% endblock title %}</title>
  <meta name="viewport" content="width=device-width,
  initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
  <div class="container">
    <header class="p-3 mb-3 border-bottom">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center
          justify-content-lg-start">
          <a class="navbar-brand" href="{% url 'home' %}">Quiz</a>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center
            mb-md-0">
            {% if user.is_authenticated %}
            <li><a href="{% url 'article_list' %}" class="nav-link px-2 link-dark">Blog</a></li>
            <li><a href="{% url 'quiz:create_category' %}" class="nav-link px-2 link-dark">Category</a></li>
            <li><a href="{% url 'quiz:create_quiz' %}" class="nav-link px-2 link-dark">Quizzes</a></li>
            <li><a href="{% url 'quiz:create_question' %}" class="nav-link px-2 link-dark">Question</a></li>
            <li><a href="{% url 'quiz:quiz_list' %}" class="nav-link px-2 link-dark" style="color: green;">Play</a></li>
            <li><a href="{% url 'quiz:scores' %}" class="nav-link px-2 link-dark">Score</a></li>
          </ul>
          <div class="dropdown text-end">
            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
              data-bs-toggle="dropdown" aria-expanded="false">
              {{ user.username }}
            </a>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
              <li><a class="dropdown-item" href="{% url 'password_change'%}">
                  Change password</a></li>
                  <li><a class="dropdown-item" href="{% url 'logout' %}" style="color: red;">Log Out</a></li>
              </li>
            </ul>
          </div>
          {% else %}
          <div class="text-end">
            <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Log
              In</a>
            <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
          </div>
          {% endif %}
        </div>
      </div>
    </header>

    <main>
      {% block content %}
      {% endblock content %}
    </main>
  </div>

  <!-- Bootstrap JavaScript Bundle -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
Hi {{ user.username }}! 
<p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a> |
<a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock content %}

templates/question_with_answers.html
{% extends "base.html" %}

{% block title %}Question with Answers{% endblock title %}

{% block content %}
  <h1>{{ question.title }}</h1>
  <h2>{{ question.question_text }}</h2>

  <form method="POST">
    {% csrf_token %}
    {% for answer in answers %}
      <label>
        <input type="radio" name="selected_answer" value="{{ answer.id }}"> {{ answer.answer_text }}
      </label>
      <br>
    {% endfor %}
    <br>
    <button type="submit">Next</button>
  </form>
{% endblock content %}